version: '2'

services:

  vtiger:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - VT_DEBUG=true
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20080:80
      - 20443:443
    volumes:
      # - ../:/var/www/html
      - vtiger:/var/lib/vtiger
    links:
      - mysql
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=vtiger
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql:rw
    ports:
      - 23306:3306

volumes:
  vtiger:
  mysql:
