# Docker
DOCKERFILE_PATH="ci/docker/Dockerfile"
DOCKER_BUILD_PATH="."
export CERTS_IMAGE_TAG="nexus.bps.net:5000/devops/certs:latest"

DOCKER_REGISTRY_UPLOAD="nexus.bps.net:5001"
DOCKER_REGISTRY_DOWNLOAD="nexus.bps.net:5000"
DOCKER_USER=$NEXUS_USER
DOCKER_PASSWORD=$NEXUS_PASSWORD

# Application
APP_IMAGE_PATH_SRC="$OPENSHIFT_PROJECT_SRC/$APP_NAME"
APP_IMAGE_PATH_DST="$OPENSHIFT_PROJECT_DST/$APP_NAME"
APP_IMAGE_PATH="$OPENSHIFT_PROJECT/$APP_NAME"
APP_BUILDER_IMAGE_TAG_LATEST="$APP_IMAGE_PATH-builder:latest"
