#!/bin/bash

source "ci/jenkins/config.sh"

# Image Tags 
IMAGE_VERSION="$GIT_COMMIT_SHORT"
APP_IMAGE_TAG="$DOCKER_REGISTRY_UPLOAD/$APP_IMAGE_PATH_DST:$IMAGE_VERSION"
APP_IMAGE_TAG_LATEST_SRC="$DOCKER_REGISTRY_UPLOAD/$APP_IMAGE_PATH_SRC:latest"       
APP_IMAGE_TAG_LATEST_DST="$DOCKER_REGISTRY_UPLOAD/$APP_IMAGE_PATH_DST:latest"
 

docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY_DOWNLOAD"

docker pull "$APP_IMAGE_TAG_LATEST_SRC"
docker tag "$APP_IMAGE_TAG_LATEST_SRC" "$APP_IMAGE_TAG"
docker tag "$APP_IMAGE_TAG_LATEST_SRC" "$APP_IMAGE_TAG_LATEST_DST"


docker push "$APP_IMAGE_TAG"
docker push "$APP_IMAGE_TAG_LATEST_DST"

